inputs:
  input_id_1:
    type: tcp
    addresses: 0.0.0.0:5514
    data_stream:
      type: logs
      dataset: nginx_access
      namespace: prod
  input_id_2:
    type: udp
    addresses: 0.0.0.0:5515
    data_stream:
      type: metrics
      dataset: windows_cpu
      namespace: prod

# File Lifecycle Management
flm:
  max_file_size: 100mb
  max_file_age: 30d
